// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package appwire

import (
	"github.com/openerp/backend/internal/config"
	"github.com/openerp/backend/internal/handler"
	"github.com/openerp/backend/internal/repository"
	"github.com/openerp/backend/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeContainer injeta todas as dependências e retorna o Container
func InitializeContainer(db *gorm.DB) *Container {
	configConfig := config.LoadConfig()
	authService := service.NewAuthService(db, configConfig)
	authHandler := handler.NewAuthHandler(authService)
	entidadeRepository := repository.NewEntidadeRepository(db)
	entidadeEnderecoService := service.NewEntidadeEnderecoService(db)
	entidadeService := service.NewEntidadeService(entidadeRepository, entidadeEnderecoService)
	entidadeHandler := handler.NewEntidadeHandler(entidadeService)
	entidadeEnderecoHandler := handler.NewEntidadeEnderecoHandler(entidadeEnderecoService)
	entidadeContatoRepository := repository.NewEntidadeContatoRepository(db)
	entidadeContatoService := service.NewEntidadeContatoService(entidadeContatoRepository, entidadeService)
	entidadeContatoHandler := handler.NewEntidadeContatoHandler(entidadeContatoService)
	entidadeDocumentoRepository := repository.NewEntidadeDocumentoRepository(db)
	entidadeDocumentoService := service.NewEntidadeDocumentoService(entidadeDocumentoRepository, entidadeService)
	entidadeDocumentoHandler := handler.NewEntidadeDocumentoHandler(entidadeDocumentoService)
	entidadeLimiteCreditoRepository := repository.NewEntidadeLimiteCreditoRepository(db)
	entidadeLimiteCreditoService := service.NewEntidadeLimiteCreditoService(db, entidadeLimiteCreditoRepository)
	entidadeLimiteCreditoHandler := handler.NewEntidadeLimiteCreditoHandler(entidadeLimiteCreditoService)
	entidadeRegimeTributarioRepository := repository.NewEntidadeRegimeTributarioRepository(db)
	entidadeRegimeTributarioService := service.NewEntidadeRegimeTributarioService(db, entidadeService, entidadeRegimeTributarioRepository)
	entidadeRegimeTributarioHandler := handler.NewEntidadeRegimeTributarioHandler(entidadeRegimeTributarioService)
	grupoEntidadeRepository := repository.NewGrupoEntidadeRepository(db)
	grupoEntidadeService := service.NewGrupoEntidadeService(grupoEntidadeRepository)
	grupoEntidadeHandler := handler.NewGrupoEntidadeHandler(grupoEntidadeService)
	produtoRepository := repository.NewProdutoRepository(db)
	produtoService := service.NewProdutoService(produtoRepository)
	produtoHandler := handler.NewProdutoHandler(produtoService)
	produtoGrupoRepository := repository.NewProdutoGrupoRepository(db)
	produtoGrupoService := service.NewProdutoGrupoService(produtoGrupoRepository)
	produtoGrupoHandler := handler.NewProdutoGrupoHandler(produtoGrupoService)
	produtoSubgrupoRepository := repository.NewProdutoSubgrupoRepository(db)
	produtoSubgrupoService := service.NewProdutoSubgrupoService(produtoSubgrupoRepository)
	produtoSubgrupoHandler := handler.NewProdutoSubgrupoHandler(produtoSubgrupoService)
	produtoMarcaRepository := repository.NewProdutoMarcaRepository(db)
	produtoMarcaService := service.NewProdutoMarcaService(produtoMarcaRepository)
	produtoMarcaHandler := handler.NewProdutoMarcaHandler(produtoMarcaService)
	produtoModeloRepository := repository.NewProdutoModeloRepository(db)
	produtoModeloService := service.NewProdutoModeloService(produtoModeloRepository)
	produtoModeloHandler := handler.NewProdutoModeloHandler(produtoModeloService)
	produtoCorRepository := repository.NewProdutoCorRepository(db)
	produtoCorService := service.NewProdutoCorService(produtoCorRepository)
	produtoCorHandler := handler.NewProdutoCorHandler(produtoCorService)
	produtoTamanhoRepository := repository.NewProdutoTamanhoRepository(db)
	produtoTamanhoService := service.NewProdutoTamanhoService(produtoTamanhoRepository)
	produtoTamanhoHandler := handler.NewProdutoTamanhoHandler(produtoTamanhoService)
	produtoVariacaoRepository := repository.NewProdutoVariacaoRepository(db)
	produtoVariacaoService := service.NewProdutoVariacaoService(produtoService, produtoCorService, produtoTamanhoService, produtoVariacaoRepository)
	produtoVariacaoHandler := handler.NewProdutoVariacaoHandler(produtoVariacaoService)
	documentoVendaRepository := repository.NewDocumentoVendaRepository(db)
	documentoVendaItemRepository := repository.NewDocumentoVendaItemRepository(db)
	tabelaPrecoProdutoRepository := repository.NewTabelaPrecoProdutoRepository(db)
	tabelaPrecoRepository := repository.NewTabelaPrecoRepository(db)
	tabelaPrecoService := service.NewTabelaPrecoService(tabelaPrecoRepository)
	tabelaPrecoProdutoService := service.NewTabelaPrecoProdutoService(tabelaPrecoProdutoRepository, tabelaPrecoService, produtoService)
	configuracaoService := service.NewConfiguracaoService(db)
	documentoVendaItemService := service.NewDocumentoVendaItemService(documentoVendaItemRepository, tabelaPrecoProdutoService, configuracaoService)
	documentoVendaPagamentoRepository := repository.NewDocumentoVendaPagamentoRepository(db)
	documentoVendaPagamentoService := service.NewDocumentoVendaPagamentoService(db, documentoVendaPagamentoRepository)
	processoRepository := repository.NewProcessoRepository(db)
	operacaoFiscalRepository := repository.NewOperacaoFiscalRepository(db)
	operacaoFiscalService := service.NewOperacaoFiscalService(operacaoFiscalRepository)
	processoService := service.NewProcessoService(processoRepository, operacaoFiscalService)
	documentoVendaItemServiceFactory := service.NewDocumentoVendaItemServiceFactory(tabelaPrecoProdutoService, configuracaoService)
	documentoVendaService := service.NewDocumentoVendaService(db, documentoVendaRepository, documentoVendaItemService, documentoVendaPagamentoService, entidadeService, processoService, documentoVendaItemServiceFactory)
	documentoVendaHandler := handler.NewDocumentoVendaHandler(documentoVendaService)
	documentoVendaItemHandler := handler.NewDocumentoVendaItemHandler(documentoVendaItemService)
	documentoVendaPagamentoHandler := handler.NewDocumentoVendaPagamentoHandler(documentoVendaService, documentoVendaPagamentoService)
	condicaoPagamentoRepository := repository.NewCondicaoPagamentoRepository(db)
	condicaoPagamentoService := service.NewCondicaoPagamentoService(condicaoPagamentoRepository)
	condicaoPagamentoHandler := handler.NewCondicaoPagamentoHandler(condicaoPagamentoService)
	operacaoFiscalHandler := handler.NewOperacaoFiscalHandler(operacaoFiscalService)
	processoHandler := handler.NewProcessoHandler(processoService)
	tabelaPrecoHandler := handler.NewTabelaPrecoHandler(tabelaPrecoService)
	tabelaPrecoProdutoHandler := handler.NewTabelaPrecoProdutoHandler(tabelaPrecoProdutoService)
	container := NewContainer(authHandler, entidadeHandler, entidadeEnderecoHandler, entidadeContatoHandler, entidadeDocumentoHandler, entidadeLimiteCreditoHandler, entidadeRegimeTributarioHandler, grupoEntidadeHandler, produtoHandler, produtoGrupoHandler, produtoSubgrupoHandler, produtoMarcaHandler, produtoModeloHandler, produtoCorHandler, produtoTamanhoHandler, produtoVariacaoHandler, documentoVendaHandler, documentoVendaItemHandler, documentoVendaPagamentoHandler, condicaoPagamentoHandler, operacaoFiscalHandler, processoHandler, tabelaPrecoHandler, tabelaPrecoProdutoHandler)
	return container
}
